# Sample configuration for RWKV7 + HRM with LoRA/QLoRA adapters
model:
  vocab_size: 65536
  d_model: 2048
  encoder:
    backend: rwkv7
    n_layers: 24
    max_seq_len: 1024
    checkpoint_path: models/blinkdl-rwkv7-g1a-1.5b/rwkv7-g1a-1.5b-20250922-ctx4096.pth
    dim_att: 2048
    dim_ffn: 7168
    head_size_a: 64
    head_size_divisor: 8
    kernel_preference: auto
    peft:
      type: lora         # options: none | lora | qlora | pissa | disha
      quantization: none # set to nf4/int8/fp8/etc for QLoRA-style training
      freeze_non_peft: true
      train_embeddings: true
      train_head: true
      train_layer_norms: true
      train_parts: ["time", "ln"]
      lora:
        r: 16
        alpha: 32
        dropout: 0.01
        load_path: ""    # optional path to resume LoRA weights
      pissa:
        r: 16
        svd_niter: 4
        load_path: ""
        init_path: ""
      disha:
        mode: bone       # bone | bat
        r: 64
        load_path: ""
  decoder:
    n_layers: 8
    max_seq_len: 1024
  hrm:
    d_model: 2048
    h_len: 8
    l_len: 64
    h_layers: 8
    l_layers: 8
    h_cycles: 12
    l_steps: 12
    approx_grad: one_step
    use_halting: true
    halting_weight: 0.05
    halting_target: 1.0
    out_dim: 2048
    deep_supervision: false
    ds_weight: 0.2
    gate_scale: 1.0
    gate_bias: 0.0
bridge:
  type: prefix
  prefix_len: 16
optim:
  name: adamw
  lr: 1.5e-4
  weight_decay: 0.0
  betas: [0.9, 0.95]
  kwargs: {}
loss:
  name: cross_entropy
  kwargs: {}
train:
  lr_scheduler:
    name: warmup_stable_decay
    kwargs:
      num_warmup_steps: 62       # ~1000 optimizer steps at batch 16
      num_stable_steps: 254      # ~4060 optimizer steps at batch 16
      num_decay_steps: 125       # ~2000 optimizer steps at batch 16
      cooldown_type: '1-sqrt'    # default; cosine also works if you prefer smoother tail
      min_lr_ratio: 0.02         # floor for the tail (tweak as needed)
  seed: 42
  batch_size: 16
  eval_batch_size: 16
  grad_accum_steps: 1
  seq_len: 256
  tgt_len: 64
  mixed_precision: bf16
  enable_tf32: true
  use_cuda_graphs: false
  fp8:
    enabled: false
    warmup_steps: 512
    format: e4m3
    recipe:
      margin: 0
      interval: 1
      amax_history_len: 16
      amax_compute_algo: max
profiling:
  nvtx:
    enabled: false
    include_data: true
    include_eval: true
